### ISSUE TITLE
onSuccessCallback이 작동하지 않습니다.

### ISSUE THREAD

**Issue by xero0001** [peoplefund-tech/react-naver-login#5]
제가 코드를 잘못짠 것일수도 있지만, 현재는 동작하지 않는것 같습니다.

react router를 통해
"/" => Home
"/login" => 네이버 로그인

이런식으로 하고 "/"을 사이트 주소, "/login"을 콜백 Url로 했습니다.

callbackUrl은 딱히 하는게 없게 설정했더니 onSuccessCallback이 자동으로 동작하지는 않네요.

대신 callbackUrl에 해당되는 페이지에서 능동적으로 window.opener.naver.successCallback() 을 부르는것으로는 잘 동작하네요.

원래 이런 의도로 사용하는 것이 맞는것인가요?

아무튼 passport가 secretKey까지 요구하는 것이 마음에 안들었는데 덕분에  네이버 로그인을 쉽고 안전하게 구현할 수 있었습니다. 정말 감사드립니다!!

**Comment by tmmoond8** [comment]
지금 구현한 방법이 팝업창을 사용한 방법인데요, 팝업 창을 사용하면 window.opner.naver.successCallback()을 호출하도록 되어있어요. 그런데 내 앱에서 로그인 페이지로 갔다가 다시 내 앱으로 돌아도록 리다이렉트 하는것은 좋은 경험이 아니라고 생각해서 callbackURL로 동작하지 않게 했습니다. 
말씀하신 것처럼 callbackURL은 제거하는 것이 맞으나, naver login을 설정할 때 필수 값이기 때문에 존재하고 있습니다. 
 이 내용은 README 업데이트와 코드를 좀 정리를 하도록 하겠습니다. 감사합니다.
